# Generated by Django 5.0.2 on 2024-02-29 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_community_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowsProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_profile', to='core.profile')),
            ],
        ),
    ]
