# Generated by Django 5.0.2 on 2024-02-29 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_post_comments_alter_followsprofiles_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followsprofiles',
            name='profile',
        ),
        migrations.AddField(
            model_name='followsprofiles',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_name', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='followsprofiles',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.profile'),
        ),
    ]
