# Generated by Django 5.0.2 on 2024-03-04 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_followsprofiles_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followsprofiles',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_id', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='followsprofiles',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='page_id', to='core.profile'),
        ),
    ]
