# Generated by Django 5.0.2 on 2024-03-04 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_followsprofiles_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followsprofiles',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followsprofiles',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile2', to=settings.AUTH_USER_MODEL),
        ),
    ]
