# Generated by Django 5.0.2 on 2024-03-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_commentary_content_alter_commentary_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
